---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app/
    name: flagger
  values:
    crd:
      create: false
    meshProvider: appmesh
    metricsServer: http://appmesh-prometheus:9090