---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
spec:
  releaseName: flagger
  chart:
    repository: https://aws.github.io/eks-charts/
    name: flagger
    version: 0.9.0
  values:
    crd:
      create: false
    meshProvider: appmesh
    metricsServer: http://appmesh-prometheus:9090